apiVersion: v1
kind: Service
metadata:
  name: redpanda-headless
  namespace: redpanda
spec:
  clusterIP: None
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
    - name: admin
      port: 9644
      targetPort: admin
    - name: schema
      port: 8081
      targetPort: schema
    - name: rpc
      port: 33145
      targetPort: rpc
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: redpanda
spec:
  type: ClusterIP
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
    - name: admin
      port: 9644
      targetPort: admin
    - name: schema
      port: 8081
      targetPort: schema
