apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prowlarr

resources:
  - namespace.yaml
  - storageclass.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - http-route.yaml