apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harness

resources:
  - namespace.yaml
  - storageclass.yaml
  - pvc.yaml
  - configmap.yaml
  - gitconfig-configmap.yaml
  - externalsecret.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - http-route.yaml
