apiVersion: v1
kind: Service
metadata:
  name: harness
  namespace: harness
  labels:
    app.kubernetes.io/name: harness
    app.kubernetes.io/instance: harness
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: harness
    app.kubernetes.io/instance: harness
