apiVersion: v1
kind: ConfigMap
metadata:
  name: orbit-www-config
data:
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_APP_URL: "https://orbit.hoytlabs.app"
  TEMPORAL_ADDRESS: "temporal:7233"
  TEMPORAL_NAMESPACE: "default"
  REPOSITORY_SERVICE_URL: "http://repository-service:50051"
  KAFKA_SERVICE_URL: "http://kafka-service:50055"
  BIFROST_ADMIN_URL: "http://bifrost:50060"
  ORBIT_REGISTRY_URL: "http://registry:5050"
  NEXT_PUBLIC_TEMPORAL_UI_URL: "https://orbit-temporal.hoytlabs.app"
  NEXT_PUBLIC_DOCS_URL: "https://orbit-docs.hoytlabs.app"
