apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - agent.yaml
  - operator.yaml
  - envoy.yaml
  - hubble.yaml
  - l2-policy.yaml
  - ip-pool.yaml