apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media
  labels:
    app.kubernetes.io/name: overseerr
    app.kubernetes.io/instance: overseerr
spec:
  type: ClusterIP
  ports:
    - port: 5055
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: overseerr
    app.kubernetes.io/instance: overseerr
